### ISSUE TITLE
[BUG] 打包工具无法正常检查原生 Autox JS 项目

### ISSUE THREAD

**Issue by RFSN** [zimoyin/Autojsx.WIFI#5]
开源作者您好。
基于插件的打包功能无法使用，日志信息如下:
[系统日志] 信息/I: 检测到打包文件存在, 不需要重新下载。如果需要重新下载请手动删除: /Users/xxxx/IdeaProjects/untitled1/.gradle/autox_apk_builder.jar
[系统日志] 警告/W: 请打开一个正确的AutoJs项目并打开其中的文件，程序将以此为基础搜索项目
[系统日志] 错误/E: 打包失败: 无法找到AutoJs项目，且当前项目不是Gradle项目，无法打包 
java.lang.IllegalArgumentException: 无法找到AutoJs项目，且当前项目不是Gradle项目，无法打包
	at github.zimo.autojsx.action.command.ApkBuilder$Companion.buildAsset(ApkBuilder.kt:139)
	at github.zimo.autojsx.action.command.ApkBuilder$Companion.buildApk$lambda$13(ApkBuilder.kt:70)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
一些想法:
通过远程服务器下载的jar 很大，
能不能优化一下，比如template.apk 可以自己自行放到工程目录，或者指定一个位置。
然后把打包的代码或者脚本，集成到插件内部来(很多人的网络环境可能不好)。
感谢大佬。

**Comment by zimoyin** [comment]
对于非 Gradle 项目。打包的时候可能需要手动打开 project.json 文件，让他在 IDEA 的编辑器窗口中作为焦点选项卡。  
当然我更推荐去主动执行打包插件 jar [下载地址](https://github.com/zimoyin/autox_apk_builder)  
  
插件下载打包插件，即便是拆分 template.apk 也需要手动下载，所以他们始终打包在一起。  
如果你需要替换 template.apk 在打包程序里面，有个选项是指定 template.apk 的路径

**Comment by zimoyin** [comment]
Autojs.WIFI 和 打包插件他们是没有关系的，Autojs.WIFI 只是负责根据当前项目自动生成一个配置文件，让打包插件去读取配置文件。打包插件并非是 Autojs.WIFI 直接调起，而是 Autojs.WIFI  调用 IDEA Runtime JRE ，让 该JRE 去调用插件。

综上：打包插件推荐手动下载，并放置在需要位置手动执行

**Comment by RFSN** [comment]
已通过聚焦 project.json  文件，依然无法正常打包，错误日志依然如上。

我已经看到您另一个打包插件的源码了，我学习一下。
感谢。

**Comment by zimoyin** [comment]
我已经复现了该严重BUG，感谢 issues
